# CommandList Version 2.1
# Created by Blacky

use strict;
use XML::Simple;
use XML::Parser;
use XML::SAX::PurePerl;
use Data::Dumper;
use File::HomeDir;
use Scalar::Util qw( reftype );


my $xml_config;
our %xml;
our $configfile			= "config.cfg";
our $config_file 		= "commands.txt";
our $config_log_file 	= "log.txt";
our $config_disabledfile = "disabled_commands.txt";
our $config_split		= 0;
our $config_sort		= 1;
our $config_unique		= 1;
our $config_show_alias = 1;
our $config_show_modlevel = 1;
our $config_show_plugin = 1;
our $config_hidecommands = 0;
our $config_hidecommand_showmodlevel = 0;
my $disabled_commands = 0;

PrintLog("------------------------------------------\n");
PrintLog("Brenbot CommandList Generator Tool V2.1\n");
PrintLog("------------------------------------------\n");
PrintLog("Run this when you edit BRenBot plugins.\n");
PrintLog("Run this when you edit Commands.xml.\n");
PrintLog("\n");

# Loads all config data
ReadConfig();

#delete existing files
unlink $config_file;
unlink $config_disabledfile;
unlink $config_log_file;

readXMLData();
my @commands = ();
my @disabled_commands = ();
my @plugin_commands = ();
my @temp_commands = ();
my @plugins = ();
my @master_commands = ();
my @unique_commands = ();
my @unique_plugins = ();
my @unique_master = ();
@commands = get_commands($xml_config, "None");
#@plugins = get_plugins();
PrintLog("\n");
#PrintLog(Dumper(@commands));
#PrintLog(Dumper(@commands));
#PrintLog(Dumper(@plugin_commands))
die;


if ( scalar(@commands) == 0 ) { PrintLog("ERROR no command's found check commands.xml.\n"); die;}
if ( scalar(@plugins) == 0 ) { PrintLog("No Plugin command's found.\n");}
my @master_commands = (@commands, @plugins);

if ( $config_unique == 1 )
{
	@unique_commands = unique_hash(@commands);
	@unique_plugins = unique_hash(@plugins);
	@unique_master = unique_hash(@master_commands);
}

if ( scalar(@unique_commands) == 0 ) { @unique_commands = @commands;  }
if ( scalar(@unique_plugins) == 0 ) { @unique_plugins = @plugins; }
if ( scalar(@unique_master) == 0 ) { @unique_master = @master_commands; }

my @sorted_commands =  sort {  $a->{name} cmp $b->{name} } @unique_commands; #sort name alphabetically
my @sorted_plugins = sort {  $a->{name} cmp $b->{name} } @unique_plugins; #sort name alphabetically
my @sorted_master = sort {  $a->{name} cmp $b->{name} } @unique_master; #sort name alphabetically

if ( $config_sort != 0 )
{
	@commands = @sorted_commands;
	@plugins = @sorted_plugins;
	@master_commands = @sorted_master;
}
else
{
	@commands = @unique_commands;
	@plugins = @unique_plugins;
	@master_commands = @unique_master;
}

# Sort by ModLevel
if ($config_sort == 2 ) 
{
	#Commands
	@sorted_commands = ();
	@sorted_commands = sort {  $a->{permission} cmp $b->{permission} } @commands;
	@commands = @sorted_commands;

	#Plugins
	@sorted_plugins = ();
	@sorted_plugins = sort {  $a->{permission} cmp $b->{permission} } @plugins;
	@plugins = @sorted_plugins;
	
	#master
	@sorted_master = ();
	@master_commands = ();
	@master_commands = (@commands, @plugins);
	@sorted_master =  sort {  $a->{permission} cmp $b->{permission} } @master_commands;
	
	if ( $config_unique == 1 ) { @master_commands = unique_hash(@master_commands); }
}

# Sort by Plugin
if ($config_sort == 3 ) 
{
	@sorted_plugins = ();
	@sorted_plugins = sort {  $a->{plugin} cmp $b->{plugin} } @plugins;
	
	@master_commands = ();
	@master_commands = (@commands, @sorted_plugins);
	@unique_master = @master_commands;
	if ( $config_unique == 1 ) { @master_commands = unique_hash(@unique_master); }
}

if ($config_sort == 4 ) 
{
	@commands = reverse @commands;
	@plugins = reverse @plugins;
	@master_commands = reverse @master_commands; #reverse array
}

if ( $disabled_commands > 0 ) { PrintLog("Disabled Commands: $disabled_commands\n"); }


if ( $config_hidecommands )
{
	WriteCreate($config_file, "[HideCommands]");
}
else 
{
	WriteCreate($config_file, "Generated by CommandList Version 2.1\n");
	WriteCreate($config_disabledfile, "Generated by CommandList Version 2.1\n");
}

if ( $config_split == 1 ) 
{
	WriteFile( $config_file, "" );
	WriteFile( $config_file, "-------------------------------------" );
	WriteFile( $config_file, "Commands" );
	WriteFile( $config_file, "-------------------------------------" );
	WriteFile( $config_file, "" );
	WriteCommands($config_file, @commands);
	WriteFile( $config_file, "" );
	WriteFile( $config_file, "-------------------------------------" );
	WriteFile( $config_file, "Plugins" );
	WriteFile( $config_file, "-------------------------------------" );
	WriteFile( $config_file, "" );
	WriteCommands($config_file, @plugins);
	WriteFile( $config_file, "-------------------------------------" );
	WriteFile( $config_file, "Disabled" );
	WriteFile( $config_file, "-------------------------------------" );
	WriteFile( $config_file, "" );
	WriteCommands($config_disabledfile, @disabled_commands);
}
else
{
	#print Dumper @master_commands;
	WriteCommands($config_file, @master_commands);
	WriteCommands($config_disabledfile, @disabled_commands);
}

PrintLog("\n");
PrintLog("Done Generating $config_file\n");

sleep(5);
exit(1);


sub ArrangeByType
{
	my $array = shift;
	my $type = shift;
	my @sorted = ();
	foreach ( @$array )
	{
		my @entrys = split (";", $_);
		my $syntax		= $entrys[$type];
		my $modlevel	= $entrys[2];
		my $plugin		= $entrys[3];
		my $alias		= $entrys[4];
		
		if ( $type == 2 ) { $modlevel = $entrys[1]; }
		if ( $type == 3 ) { $plugin = $entrys[1]; }
		
		if ( defined($alias) ) { 
			push(@sorted, ";$syntax;$modlevel;$plugin;$alias");
		}
		else {
			push(@sorted, ";$syntax;$modlevel;$plugin;");
		}
	}
	return @sorted;
}

sub ArrangeByHash
{
	my $array = shift;
	my $type = shift;
	my @sorted = ();
	foreach ( @$array )
	{
		my @entrys = split (";", $_);
		my $syntax		= $entrys[$type];
		my $modlevel	= $entrys[2];
		my $plugin		= $entrys[3];
		my $alias		= $entrys[4];
		
		if ( $type == 2 ) { $modlevel = $entrys[1]; }
		if ( $type == 3 ) { $plugin = $entrys[1]; }
		
		if ( defined($alias) ) { 
			push(@sorted, ";$syntax;$modlevel;$plugin;$alias");
		}
		else {
			push(@sorted, ";$syntax;$modlevel;$plugin;");
		}
	}
	return @sorted;
}

sub unique_commands_verbose
{
	my %seen;
	my @array = (@_);
	my @unique = ();
	foreach my $value (@array) 
	{
		my @entrys = split (";", $value);
		my $entry = $entrys[1];
		if ( $entry =~ /^(.+?)\s.+$/ ) 
		{
			my $command = $1;
			if (!defined($seen{$command})) { 
				push @unique, $value;
				$seen{$command} = 1;
			}
			else{
				PrintLog("Duplicate Command: $command\n");
			}
		}
		else{
			PrintLog("Command $entry syntax ERROR did not match command.\n");
		}
	}
	return @unique;
}


#sub unique_hash_ref
#{
#	my @ref = (@_);
#	my %seen;
#	my $removed = 0;
#	for my $i (0 .. @ref) {
#		my $item = $ref->[$i];
#		$seen{$item->{id}}++ ? $removed++ : ($ref->[$i-$removed] = $item);
#	}
#	splice @$ref,-$removed;
#}
#


sub unique_hash3
{
	my %seen;
	my @array = (@_);
	my @unique = ();
	my $command;

}

sub unique_hash
{
	my %seen;
	my @array = (@_);
	my @unique = ();
	my $command;
	
	#PrintLog(Dumper(@array));
	
	foreach my $k (@array) 
	{
		if ( $k->{name} )
		{
			if (!defined($seen{$k->{name}})) { 
				push @unique, $k;
				$seen{$command} = 1;
			}
		}
	}
	return @unique;
}

sub unique_hash2
{
	my $ref = $_[0];
	my %seen;
	my $removed = 0;
	for my $i (0 .. @$ref-1) {
		my $item = $ref->[$i];
		$seen{$item->{name}}++ ? $removed++ : ($ref->[$i-$removed] = $item);
		if (defined($seen{$item->{name}})) { 
			PrintLog("Duplicate entry found " . $item->{name} . " Plugin: " . $item->{plugin} . "\n");
		}
		
	}
	splice @$ref,-$removed;
}


sub unique_hash_grep
{
	my @ref = (@_);
	my $ref = [ map { +{ id => $_ } } qw{a b c b} ];
	my %seen;
	@$ref = grep { ! $seen{$_->{id}}++ } @$ref;
	dd $ref;
}



sub unique_commands
{
	my %seen;
	my @array = (@_);
	my @unique = ();
	my $command = undef;
	foreach my $value (@array) 
	{
		my @entrys = split (";", $value);
		my $entry = $entrys[1];
		if ( $entry =~ /^(.+?)\s.+$/ ) 
		{
			my $command = $1;
			if (!defined($seen{$command})) { 
				push @unique, $value;
				$seen{$command} = 1;
			}
		}
	}
	return @unique;
}

sub get_syntax_command_name($)
{
	my $syntax = shift;
	my $command = undef;
	if ( $syntax =~ /^(.+?)\s.+$/ || $syntax =~ /^(.+)$/ ) 
	{
		$command = $1;
	}
	else
	{
		PrintLog("Syntax get command failed $syntax\n");
	}
	return $command;
}

sub WriteCommands($)
{
	my $file = shift;
	my @array = (@_);
	foreach ( @array )
	{
		my $name 		= $_->{name};
		my $syntax		= $_->{syntax};
		my $modlevel	= $_->{permission};
		my $plugin		= $_->{plugin};
		my $alias		= $_->{alias};
	
		
		if ( $config_hidecommands == 0 ) 
		{
			WriteFile( $file, "!$syntax" );
			WriteFile( $file, "$alias" ) if ( defined($alias) && $alias ne "None" && $config_show_alias == 1 );					
			WriteFile( $file, "$modlevel" ) if ( defined($modlevel) && $config_show_modlevel == 1);
			WriteFile( $file, "Plugin: $plugin" ) if ( defined($plugin) && $plugin ne "" && $plugin ne "None" && $config_show_plugin == 1 );
			WriteFile( $file, "" );
		}
		else
		{
			if ( $syntax =~ /^(.+?)\s.+$/ ) {
				if ( $config_hidecommand_showmodlevel == 1 ) {
					WriteFile( $file, '!'.$1." = 1 ;$modlevel" );
				}
				else
				{
					WriteFile( $file, '!'.$1." = 1 " );
				}
			}
			else{
				PrintLog("Command $syntax syntax ERROR did not match command.\n");
			}
		}
	}
}

sub readXMLData
{
	my $xmlOld = $xml_config;
	$xml_config = "";
	my $error;
	eval
	{
		PrintLog("Reading commands.xml \n");
		$xml_config = XMLin("commands.xml", ForceArray => [ 'group' ] );
		while ( my ($k, $v) = each %{$xml_config->{command}} )
		{
			$v->{syntax}->{value} =~ s/&gt;/>/gi;
			$v->{syntax}->{value} =~ s/&lt;/</gi;
		}
	}
	or $error = $@;
	if ( $error )
	{
		if ( ! -e "commands.xml")
		{
			PrintLog("commands.xml doesn't exist! commands.xml must be in the same folder as CommandList_Generator.exe.\n");
		}
		else
		{
			PrintLog("Error while reading commands.xml! \n");
			PrintLog("$error\n");
		}
		sleep(5);
		exit(1);
	}
}

sub get_plugins
{
	unless(opendir(DATADIR, "plugins/"))
	{
		PrintLog("No plugins folder found.\n");
		return ();
	}

	my @plugin_files;
	@plugin_files = grep(/\.pm$/i,readdir(DATADIR));
	foreach (@plugin_files)
	{
		my $plugin = $_;
		my $error;
		$plugin =~ s/\.pm$//g;
		PrintLog("Reading $plugin.xml\n");
		eval
		{
			$xml{$plugin} = XMLin( "plugins/$plugin.xml", ForceArray => [ qw(event group command hook) ], KeyAttr => [ 'name', 'key', 'id', 'event' ] );
		}
		or $error=$@;
		if ($error)
		{
			PrintLog("Error while reading $plugin.xml!");
			PrintLog("$error");
			next;
		}
		#PrintLog(Dumper(get_commands($xml{$plugin}, $plugin)));
		@plugin_commands = (@plugin_commands, get_commands($xml{$plugin}, $plugin) );
	}
	return @plugin_commands; 
}

sub get_plugins3
{
	unless(opendir(DATADIR, "plugins/"))
	{
		PrintLog("No plugins folder found.\n");
		return ();
	}

	my @plugin_files;
	@plugin_files = grep(/\.pm$/i,readdir(DATADIR));
	my @tmp;
	my @temp2;
	foreach (@plugin_files)
	{
		my $plugin = $_;
		my $error;
		$plugin =~ s/\.pm$//g;
		PrintLog("Reading $plugin.xml\n");
		eval
		{
			$xml{$plugin} = XMLin( "plugins/$plugin.xml", ForceArray => [ qw(event group command hook) ], KeyAttr => [ 'name', 'key', 'id', 'event' ] );
		}
		or $error=$@;
		if ($error)
		{
			PrintLog("Error while reading $plugin.xml!");
			PrintLog("$error");
			next;
		}
		@temp2 = get_commands($xml{$plugin}, $plugin);
		#@tmp = (@tmp, get_commands($xml{$plugin}, $plugin) );
		push(@tmp, @temp2);
		
		#PrintLog("$xml{$plugin} $plugin\n");
		#PrintLog(Dumper(@temp2));
		
	}
	#PrintLog(Dumper(@tmp));
	return @tmp; 
}

sub get_plugins2
{
	unless(opendir(DATADIR, "plugins/"))
	{
		PrintLog("No plugins folder found.\n");
		return ();
	}

	my @plugin_files;
	@plugin_files = grep(/\.pm$/i,readdir(DATADIR));

	foreach (@plugin_files)
	{
		my $plugin = $_;
		my $error;
		my @tmpcmds;
		$plugin =~ s/\.pm$//g;
		PrintLog("Reading $plugin.xml\n");
		eval
		{
			$xml{$plugin} = XMLin( "plugins/$plugin.xml", ForceArray => [ qw(event group command hook) ], KeyAttr => [ 'name', 'key', 'id', 'event' ] );
		}
		or $error=$@;
		if ($error)
		{
			PrintLog("Error while reading $plugin.xml!");
			PrintLog("$error");
			next;
		}	
		@plugin_commands = (@plugin_commands, get_commands($xml{$plugin}, $plugin) );
		PrintLog(Dumper(@plugin_commands));
	}
	
	PrintLog(Dumper(@plugin_commands));
	return @plugin_commands; 
}


#Fix script form crashing due to xml config error and check for other config errors
#Detects is value is Hash or Array, Think we have Duplicate Entry if an array. 
#Not to be used on 'group' or 'alias' as they are multi array config options. 
#'enabled' => [
#              {
#                'value' => '1'
#              },
#              {
#                'value' => '0'
#              }		
	 
sub DetectInvalidConfig($$$)
{
	my $key = shift;
	my $value = shift;
	my $c = shift;
	
	if ( ref($value) eq 'HASH' )
	{
		if ( ref($value->{enabled}) eq 'ARRAY' )
		{
			PrintLog("Duplicate xml entry detected $key enabled.\n");
			PrintLog(Dumper($value));
			return 1;
		}
		elsif ( ref($value->{syntax}) eq 'ARRAY' )
		{
			PrintLog("Duplicate xml entry detected $key syntax.\n");
			PrintLog(Dumper($value));
			return 1;
		}
		elsif ( ref($value->{help}) eq 'ARRAY' )
		{
			PrintLog("Duplicate xml entry detected $key help.\n");
			PrintLog(Dumper($value));
			return 1;
		}
		elsif ( ref($value->{hideInHelp}) eq 'ARRAY' )
		{
			PrintLog("Duplicate xml entry detected $key hideInHelp.\n");
			PrintLog(Dumper($value));
			return 1;
		}
		elsif ( ref($value->{permission}) eq 'ARRAY' )
		{
			PrintLog("Duplicate xml entry detected $key permission.\n");
			PrintLog(Dumper($value));
			return 1;
		}
	}
	else
	{
		PrintLog(Dumper($value));
		PrintLog("Invalid value detected $key $value.\n");
		return 1;
	}
	
	if ($key =~ /[A-Z]/ ) 
	{
        PrintLog("Warning uppercase config name detected $key\n");
    }
	
	my $command;
	my $syntax = $value->{syntax}->{value};
	$command = $1 if ( $syntax =~ /^(.+?)\s.+$/ );
	if ($syntax eq uc $syntax || $command =~ /[A-Z]/)
	{
        PrintLog("Warning uppercase syntax detected $syntax\n");
    }
	if( $syntax =~ /\s\>.+?\<\s/ ) 
	{
		PrintLog("Backwards Brackets Detected $syntax\n");
	}
	
	return 0;
}

sub get_commands($$)
{
	my $xml    = shift;
	my $plugin = shift;

	my $c = $xml->{command};
	#my @commands = ();
	my %seen;

	#return !defined($c);
	while (my ($key, $value) = each %{$c})
	{
		next if DetectInvalidConfig($key,$value,$c);
		my $alias;
		my $syn = "$value->{syntax}->{value}";
		$syn =~ s/\!//g;
		my $sname = get_syntax_command_name($syn);
		my $slength = length($sname);
		my $temp = substr($sname, $slength + 1);
		$sname = lc($sname);
		$syn = $sname . $temp;
		my $syntax = "$syn - $value->{help}->{value}";
		my $permission = get_permission($value->{permission}->{level});
		my $modlevel = "Mod Level: $permission";
		
		if ( $value->{alias} )
		{
			$alias = "Command Alias: ";
			if ( ref($value->{alias}) eq "ARRAY" )
			{
				foreach ( @{$value->{alias}} )
				{
					my %alias = ( 'name' => $_, 'alias' => $key );
					$alias = $alias . "!" . $alias{name} . " ";
				}
			}
			else
			{
				my %alias = ( 'name' => $value->{alias}, 'alias' => $key );
				$alias = $alias . "!" . $alias{name} . " ";
			}
		}
		
		my $enabled = $value->{enabled}->{value};
		$plugin = "None" if ( $plugin eq "" || !defined($plugin));
		$alias = "None" if ( $alias eq "" || !defined($alias));
		if ( $enabled == 1 )
		{
			#push @temp_commands, $value;
			push(@commands, { name => $sname, enabled => $enabled, syntax => $syntax, permission => $permission, plugin => $plugin, alias => $alias });
			PrintLog(Dumper(@commands));
		}
		else
		{			
			push @disabled_commands, { name => $sname, enabled => $enabled, syntax => $syntax, permission => $permission, plugin => $plugin, alias => $alias };
			$disabled_commands++
		}
	}
	#PrintLog(Dumper(@temp_commands));
	
	return @commands;	
}

sub get_permission($)
{
	my $permission = shift;
	my $permission_name = "None";
	if ( $permission == 0 ) { $permission_name = "Normal Ingame Users"; }
	elsif ( $permission == 1 ) { $permission_name = "Temporary Moderators"; }
	elsif ( $permission == 2 ) { $permission_name = "Half Moderators"; }
	elsif ( $permission == 3 ) { $permission_name = "Full Moderators"; }
	elsif ( $permission == 4 ) { $permission_name = "Administrators"; }
	elsif ( $permission == 5 ) { $permission_name = "Administrators"; }
	return $permission_name;
}

sub ReadConfig
{
	my $fh;
	open ( $fh, $configfile ) or die "Config_File_Read: $!,";
	while ( <$fh> )
	{
		if ( $_ !~ m/^\#/ && $_ !~ m/^\s+$/ )		# If the line starts with a hash or is blank ignore it
		{
			if (/^\s*File\s*\=\s*(\S+)/i)								{ $config_file = $1; }
			if (/^\s*Disabled_File\s*\=\s*(\S+)/i)						{ $config_disabledfile = $1; }
			if (/^\s*Split\s*=\s*(\d+)/i)		 						{ $config_split = $1; }
			if (/^\s*Sort\s*=\s*(\d+)/i)		 						{ $config_sort = $1; }
			if (/^\s*UniqueCommands\s*=\s*(\d+)/i)						{ $config_unique = $1; }
			if (/^\s*Show_Alias\s*=\s*(\d+)/i)							{ $config_show_alias = $1; }
			if (/^\s*Show_ModLevel\s*=\s*(\d+)/i)						{ $config_show_modlevel = $1; }
			if (/^\s*Show_Plugin\s*=\s*(\d+)/i)							{ $config_show_plugin = $1; }
			if (/^\s*HideCommands\s*=\s*(\d+)/i)						{ $config_hidecommands = $1; } 
			if (/^\s*HideCommands_ShowModLevel\s*=\s*(\d+)/i)			{ $config_hidecommand_showmodlevel = $1; }
		}
	}

	my $config_error = undef;
	$config_error .= "File " unless ($config_file);
	if ($config_error)
	{
		PrintLog( "[Config] ERROR: Missing config file option(s): $config_error" );
		sleep ( 10 );
		exit;
	}

	close $fh;
}


sub PrintLog($)
{
	my $msg = shift;
	print($msg);
	chomp $msg;
	WriteFile($config_log_file, $msg);
}

sub WriteCreate($$)
{
	my $file = shift;
	my $msg	= shift;
	open ( my $fh, '>' . $file );
	print $fh "$msg\n";
	close $fh;
}

sub WriteFile($$)
{
	my $file = shift;
	my $msg	= shift;
	open ( my $fh, '>>' . $file );
	print $fh "$msg\n";
	close $fh;
}