# CommandList Version 2.0 Build 1
# Created by Blacky

use strict;
use XML::Simple;
use XML::Parser;
use XML::SAX::PurePerl;
use Data::Dumper;
use File::HomeDir;


my $xml_config;
our %xml;
our $configfile			= "config.cfg";
our $config_file 		= "commands.txt";
our $config_split		= 0;
our $config_sort		= 0;
our $config_unique		= 0;
our $config_hidecommands = 0;
our $config_hidecommand_showmodlevel = 0;
my $disabled_commands = 0;


print "\n";
print "Brenbot CommandList Generator Tool V2.0\n";
print "\n";
print "Generates Commands.txt.\n";
print "Run this when you add/remove BRenBot plugins.\n";
print "Run this when you add/remove aliases for commands.\n";
print "\n";

# Loads all config data
ReadConfig();
readXMLData();
my @commands = ();
my @plugins = ();
my @mastercommands = ();
my @uniquecommands = ();
my @uniqueplugins = ();
my @uniquemaster = ();
@commands = get_commands($xml_config, "");
@plugins = get_plugins();
print "\n";

#if ( scalar(@commands) == 0 ) { print "ERROR no command's found check commands.xml.\n"; sleep(5); exit; }
if ( scalar(@commands) == 0 ) { print "ERROR no command's found check commands.xml.\n"; }
if ( scalar(@plugins) == 0 ) { print "No Plugin command's found.\n"; }

my @mastercommands = (@commands, @plugins);

if ( $config_unique == 1 )
{
	@uniquecommands = unique_commands(@commands);
	@uniqueplugins = unique_commands(@plugins);
	@uniquemaster = unique_commands_verbose(@mastercommands);
}

if ( scalar(@uniquecommands) == 0 ) { @uniquecommands = @commands;  }
if ( scalar(@uniqueplugins) == 0 ) { @uniqueplugins = @plugins; }
if ( scalar(@uniquemaster) == 0 ) { @uniquemaster = @mastercommands; }

my @sorted_commands = sort @uniquecommands; #sort alphabetically
my @sorted_plugins = sort @uniqueplugins; #sort alphabetically
my @sorted_master = sort @uniquemaster; #sort alphabetically

if ( $config_sort != 0 )
{
	@commands = @sorted_commands;
	@plugins = @sorted_plugins;
	@mastercommands = @sorted_master;
}
else
{
	@commands = @uniquecommands;
	@plugins = @uniqueplugins;
	@mastercommands = @uniquemaster;
}

# Sort by ModLevel
if ($config_sort == 2 ) 
{
	#Commands
	# Since the array element is a single string put the modlevel name in the front of the string so we can sort it by the modlevel
	@sorted_commands = ();
	@sorted_commands = ArrangeByType(\@commands, 2); #Pass array by Reference, type
	@sorted_commands = sort @sorted_commands;
	
	#Now that it is sorted by the modlevel create a new array with our original format
	@commands = ();
	@commands = ArrangeByType(\@sorted_commands, 2); #Pass array by Reference, type

	#Plugins
	# Since the array element is a single string put the modlevel name in the front of the string so we can sort it by the modlevel
	@sorted_plugins = ();
	@sorted_plugins = ArrangeByType(\@plugins, 2); #Pass array by Reference, type
	@sorted_plugins = sort @sorted_plugins;
	
	#Now that it is sorted by the modlevel create a new array with our original format
	@plugins = ();
	@plugins = ArrangeByType(\@sorted_plugins, 2); #Pass array by Reference, type
	
	#master
	#Now that it is sorted by the modlevel create a new array with our original format
	my @sorted = (@sorted_commands, @sorted_plugins);
	@sorted = sort @sorted;
	@mastercommands = ArrangeByType(\@sorted, 2);
	if ( $config_unique == 1 ) { @mastercommands = unique_commands(@mastercommands); }
}

# Sort by Plugin
if ($config_sort == 3 ) 
{
	# Since the array element is a single string put the plugin name in the front of the string so we can sort it by the plugin name
	@sorted_plugins = ();
	@sorted_plugins = ArrangeByType(\@plugins, 3); #Pass array by Reference, type
	@sorted_plugins = sort @sorted_plugins;
	
	#Now that it is sorted by the plugin name create a new array with our original format
	@plugins = ();
	@plugins = ArrangeByType(\@sorted_plugins, 3); #Pass array by Reference, type
	#print Dumper @plugins;
	
	@mastercommands = ();
	@mastercommands = (@commands, @plugins);
	@uniquemaster = @mastercommands;
	if ( $config_unique == 1 ) { @mastercommands = unique_commands(@uniquemaster); }
}

if ($config_sort == 4 ) 
{
	@commands = reverse @commands;
	@plugins = reverse @plugins;
	@mastercommands = reverse @mastercommands; #reverse array
}

if ( $disabled_commands > 0 ) { print "Disabled Commands: $disabled_commands"}

unlink "Commands.txt";
CommandCreate("Generated by CommandList Version 2.0\n");
if ( $config_split == 1 ) 
{
	CommandWrite( "" );
	CommandWrite( "-------------------------------------" );
	CommandWrite( "Commands" );
	CommandWrite( "-------------------------------------" );
	CommandWrite( "" );
	WriteCommands(@commands);
	CommandWrite( "" );
	CommandWrite( "-------------------------------------" );
	CommandWrite( "Plugins" );
	CommandWrite( "-------------------------------------" );
	CommandWrite( "" );
	WriteCommands(@plugins);
}
else
{
	WriteCommands(@mastercommands);
}

print "\n";
print "Commands.txt Done\n";

sleep(5);
exit(1);


sub ArrangeByType
{
	my $array = shift;
	my $type = shift;
	my @sorted = ();
	foreach ( @$array )
	{
		my @entrys = split (";", $_);
		my $syntax		= $entrys[$type];
		my $modlevel	= $entrys[2];
		my $plugin		= $entrys[3];
		my $alias		= $entrys[4];
		
		if ( $type == 2 ) { $modlevel = $entrys[1]; }
		if ( $type == 3 ) { $plugin = $entrys[1]; }
		
		if ( defined($alias) ) { 
			push(@sorted, ";$syntax;$modlevel;$plugin;$alias");
		}
		else {
			push(@sorted, ";$syntax;$modlevel;$plugin;");
		}
	}
	return @sorted;
}

sub unique_commands_verbose
{
	my %seen;
	my @array = (@_);
	my @unique = ();
	foreach my $value (@array) 
	{
		my @entrys = split (";", $value);
		my $entry = $entrys[1];
		if ( $entry =~ /^(.+?)\s.+$/ ) 
		{
			my $command = $1;
			if (!defined($seen{$command})) { 
				push @unique, $value;
				$seen{$command} = 1;
			}
			else{
				print "Duplicate Command: $command\n"; #print "$entry \n";
			}
		}
		else{
			print "Command $entry syntax ERROR did not match command.\n";
		}
	}
	return @unique;
}

sub unique_commands
{
	my %seen;
	my @array = (@_);
	my @unique = ();
	foreach my $value (@array) 
	{
		my @entrys = split (";", $value);
		my $entry = $entrys[1];
		if ( $entry =~ /^(.+?)\s.+$/ ) 
		{
			my $command = $1;
			if (!defined($seen{$command})) { 
				push @unique, $value;
				$seen{$command} = 1;
			}
		}
	}
	return @unique;
}

sub WriteCommands
{
	my @array = (@_);
	foreach ( @array )
	{
		my @entrys = split (";", $_);
		my $syntax		= $entrys[1];
		my $modlevel	= $entrys[2];
		my $plugin		= $entrys[3];
		my $alias		= $entrys[4];
		
		if ( $config_hidecommands == 0 ) 
		{
			CommandWrite( "!$syntax" );
			CommandWrite( "$alias" ) if ( defined($alias) );
			CommandWrite( "$modlevel" );
			CommandWrite( "Plugin: $plugin" ) if ( defined($plugin) && $plugin ne "" );
			CommandWrite( "" );
		}
		else
		{
			if ( $syntax =~ /^(.+?)\s.+$/ ) {
				if ( $config_hidecommand_showmodlevel == 1 ) {
					CommandWrite( '!'.$1." = 1 ;$modlevel" );
				}
				else
				{
					CommandWrite( '!'.$1." = 1 " );
				}
			}
			else{
				print "Command $syntax syntax ERROR did not match command.\n";
			}
		}
	}
}

sub readXMLData
{
	my $xmlOld = $xml_config;
	$xml_config = "";
	my $error;
	eval
	{
		print "Reading commands.xml \n";
		$xml_config = XMLin("commands.xml", ForceArray => [ 'group' ] );
		while ( my ($k, $v) = each %{$xml_config->{command}} )
		{
			$v->{syntax}->{value} =~ s/&gt;/>/gi;
			$v->{syntax}->{value} =~ s/&lt;/</gi;
		}
	}
	or $error = $@;
	if ( $error )
	{
		if ( ! -e "commands.xml")
		{
			print "commands.xml doesn't exist! commands.xml must be in the same folder as CommandList_Generator.exe.\n";
		}
		else
		{
			print "Error while reading commands.xml! \n";
			print "$error\n";
		}
		sleep(5);
		exit(1);
	}
}

sub get_plugins
{
	unless(opendir(DATADIR, "plugins/"))
	{
		print "No plugins folder found.\n";
		return ();
	}

	my @plugin_files;
	@plugin_files = grep(/\.pm$/i,readdir(DATADIR));
	my @masterplugins = ();

	foreach (@plugin_files)
	{
		my $plugin = $_;
		my $error;
		$plugin =~ s/\.pm$//g;
		print "Reading $plugin.xml\n";
		eval
		{
			$xml{$plugin} = XMLin( "plugins/$plugin.xml", ForceArray => [ qw(event group command hook) ], KeyAttr => [ 'name', 'key', 'id', 'event' ] );
		}
		or $error=$@;
		if ($error)
		{
			print "Error while reading $plugin.xml!";
			print "$error";
			next;
		}	
		@masterplugins = (@masterplugins, get_commands($xml{$plugin}, $plugin) );
	}
	return @masterplugins; 
}

sub get_commands
{
	my $xml    = shift;
	my $plugin = shift;
	$plugin = "" if ( !defined($plugin) );

	my $c = $xml->{command};
	my @commands = ();

	return if ( !defined($c) );
	while (my ($key, $value) = each %{$c})
	{
		my $alias;
		if ( $value->{enabled}->{value} == 1 )
		{
			my $syn = "$value->{syntax}->{value}";
			$syn =~ s/\!//g;
			my $syntax = "$syn - $value->{help}->{value}";
			if ( $value->{alias} )
			{
				$alias = "Command Alias: ";
				if ( ref($value->{alias}) eq "ARRAY" )
				{
					foreach ( @{$value->{alias}} )
					{
						my %alias = ( 'name' => $_, 'alias' => $key );
						$alias = $alias . "!" . $alias{name} . " ";
					}
				}
				else
				{
					my %alias = ( 'name' => $value->{alias}, 'alias' => $key );
					$alias = $alias . "!" . $alias{name} . " ";
				}
			}
			
			my $permission = get_permission($value->{permission}->{level});
			my $modlevel = "Mod Level: $permission";
			if ( defined($alias) ) { 
				push(@commands, ";$syntax;$modlevel;$plugin;$alias");
			}
			else {
				push(@commands, ";$syntax;$modlevel;$plugin");
			}
		}
		else { $disabled_commands++ }
	}
	return @commands;
}

sub get_permission
{
	my $permission = shift;
	my $permission_name = "None";
	if ( $permission == 0 ) { $permission_name = "Normal Ingame Users"; }
	elsif ( $permission == 1 ) { $permission_name = "Temporary Moderators"; }
	elsif ( $permission == 2 ) { $permission_name = "Half Moderators"; }
	elsif ( $permission == 3 ) { $permission_name = "Full Moderators"; }
	elsif ( $permission == 4 ) { $permission_name = "Administrators"; }
	elsif ( $permission == 5 ) { $permission_name = "Administrators"; }
	return $permission_name;
}

sub ReadConfig
{
	my $fh;
	open ( $fh, $configfile ) or die "Config_File_Read: $!,";
	while ( <$fh> )
	{
		if ( $_ !~ m/^\#/ && $_ !~ m/^\s+$/ )		# If the line starts with a hash or is blank ignore it
		{
			if (/^\s*File\s*\=\s*(\S+)/i)								{ $config_file = $1; }
			if (/^\s*Split\s*=\s*(\d+)/i)		 						{ $config_split = $1; }
			if (/^\s*Sort\s*=\s*(\d+)/i)		 						{ $config_sort = $1; }
			if (/^\s*UniqueCommands\s*=\s*(\d+)/i)						{ $config_unique = $1; }
			if (/^\s*Show_Aliase\s*=\s*(\d+)/i)							{ $config_show_aliase = $1; }
			if (/^\s*HideCommands\s*=\s*(\d+)/i)						{ $config_hidecommands = $1; } 
			if (/^\s*HideCommands_ShowModLevel\s*=\s*(\d+)/i)			{ $config_hidecommand_showmodlevel = $1; }
		}
	}

	my $config_error;
	$config_error .= "File " if (!$config_file);
	if ($config_error)
	{
		main::console_output ( "[Config] ERROR: Missing config file option(s): $config_error" );
		sleep ( 10 );
		exit;
	}

	close $fh;
}

sub CommandCreate
{
	my $msg	= shift;
	my $COMMANDFILE;
	open ( $COMMANDFILE, '>' . $config_file );
	print $COMMANDFILE "$msg\n";
	close $COMMANDFILE;
}

sub CommandWrite
{
	my $msg	= shift;
	my $COMMANDFILE;
	open ( $COMMANDFILE, '>>' . $config_file );
	print $COMMANDFILE "$msg\n";
	close $COMMANDFILE;
}

sub Debug
{
	my $msg	= shift;
	my $COMMANDFILE;
	open ( $COMMANDFILE, '>>debug.txt' );
	print $COMMANDFILE "$msg\n";
	close $COMMANDFILE;
}